export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const RESET_ALL_STATES = "RESET_ALL_STATES";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const UPDATE_BATTLE = "UPDATE_BATTLE";
export const UPDATE_INBATTLE = "UPDATE_INBATTLE";
export const UPDATE_AFTER_BATTLE = "UPDATE_AFTER_BATTLE";
export const CLEAR_BATTLE = "CLEAR_BATTLE";
